### ISSUE TITLE
Changes to sexplib break SerAPI build

### ISSUE THREAD

**Issue by psteckler** [ejgallego/coq-serapi#34] opened 2017-04-07 22:06 UTC
In sertop/sertop_sexp.ml, there are calls to `Conv.Exn_converter.add`, which doesn't seem to exist in recent versions of sexplib. In OPAM, OCaml 4.03 and 4.04 use sexplib 113.33.00. So SerAPI won't build with those versions of OCaml  in OPAM.

Instead, sexplib now has `add_auto` and `add_slow`.

**Comment by ejgallego** [comment] 2017-04-08 11:52
What branch are you talking about? If it is for master, for now you must use the stm-branch + coq's stm+parsing_api, I'll merge it back to master as soon as coq/coq#441 is merged upstream.

**Comment by ejgallego** [comment] 2017-04-08 12:42
It looks like you must update your sexplib. Confirmed that this works for me with sexplib v0.9.1 and the `coq-master-stm` branch.

Noe that SerAPI requires 4.04.0 and sexplib > v0.9.0

**Closed** 2017-04-08 12:42 UTC

**Comment by psteckler** [comment] 2017-04-08 13:19
It didn't work for me with OCaml 4.04.0 in OPAM, and the sexplib that you get with that. I also tried 4.03.0, same issue.

I was using the branches you mention for Coq and for SerAPI.

**Comment by psteckler** [comment] 2017-04-08 13:25
I will try downgrading sexplib to see if that works.

**Comment by ejgallego** [comment] 2017-04-08 14:59
You need to _upgrade_ sexplib, note that `v0.9.1 >= 113.33`. My config:
```
ppx_import                        1.1  A syntax extension for importing declarat
sexplib                        v0.9.1  Library for serializing OCaml values to a
ppx_sexp_conv                  v0.9.0  Generation of S-expression conversion fun
```

**Comment by psteckler** [comment] 2017-04-10 17:51
Of course, that's obvious from the version numbers. :-)

`opam upgrade` makes things work, thanks.

**Comment by ejgallego** [comment] 2017-04-10 19:44
:) there's a reason old Debian picked that scheme thou ;)
