### ISSUE TITLE
Deserialization of Coq's "generic arguments" is not supported.

### ISSUE THREAD

**Issue by riswords** [ejgallego/coq-serapi#41] opened 2017-12-29 22:10 UTC
If I add a small example proof like this:

```
(Add () "Example test_orb1: (orb true false) = true. Proof. simpl. reflexivity. Qed.")
(Query () (Ast 4))
```
at the beginning of a sertop session, I see `Added` responses with IDs 2-6. So ID 2 is the definition, 4 is the `simpl` tactic, etc. I would expect to be able to use the `Ast` query command to see which tactics were used. However, if I issue this command:

I see this result:
```
(Answer 1 Ack)
(Answer 1(ObjList((CoqAst((((fname"")(line_nb 2)(bol_pos 44)(line_nb_last 2)(bol_pos_last 44)(bp 51)(ep 57)))(VernacExtend(VernacSolve 0)("XXX Raw GenARG""XXX Raw GenARG""XXX Raw GenARG""XXX Raw GenARG")))))))
(Answer 1 Completed)
```

In place of "XXX Raw GenARG", I would like to see something about the `simpl` tactic somewhere in the result. Is that something that could be fixed? Or is there an alternative way to access information about tactics used in a proof?

**Comment by riswords** [comment] 2017-12-29 22:14
As an additional note on this, if I try to use the `Print` command on the `CoqAst` object in that query result, I get a segmentation fault that crashes sertop:

```
(Print () (CoqAst((((fname"")(line_nb 2)(bol_pos 44)(line_nb_last 2)(bol_pos_last 44)(bp 51)(ep 57)))(VernacExtend(VernacSolve 0)("XXX Raw GenARG""XXX Raw GenARG""XXX Raw GenARG""XXX Raw GenARG")))))
(Answer 5 Ack)
Segmentation fault (core dumped)
```

**Comment by ejgallego** [comment] 2017-12-30 03:48
Oh indeed! This is a bug due to some sloppy programming on my part. I will fix ASAP.

The reason is that tactics are defined in a plugins, thus some black-magic is needed in order to properly handle them. I did a first attempt some time ago, but then decided to switch to a new model which is, up to this date, yet unfinished.

Sorry for the trouble.

**Comment by riswords** [comment] 2018-01-03 18:07
Thanks so much, and no need to apologize, I appreciate all of the work you've done on SerAPI!

**Comment by ejgallego** [comment] 2018-01-09 18:47
Ok, fc40bf6 should solve the first part of the issue [serialization], however, I am sure I have missed some cases, please test and report back strange outputs.

The second part of the issue [parsing back generic arguments] will take a bit more of time, but it is on the roadmap. For now, I recommend using `Query`'s `(pp (pp_format ...))` parameter to workaround the parsing back issue.

**Comment by ejgallego** [comment] 2018-01-13 22:18
Segmentation fault fixed in c94c17f671e3a90a01faa5629c4cf4b17972dc31 , deserialization of genargs not soon.

**Comment by ejgallego** [comment] 2018-01-13 22:53
> deserialization of genargs not soon.

@riswords , how much do you need to be able to de-serialize tactics? Can you live with the suggested workaround of setting `(pp_format PpStr)`?

If you really need it I'll try to fully close this issue soon, otherwise I will postpone it after 8.9.

**Comment by riswords** [comment] 2018-01-16 01:26
I apologize for the delay in responding. I have done some testing with the serialization, and I noticed two things: 
1. The `subst` tactic is tagged as `TacAlias` in the CoqAst. I'm not sure if this is an expected consequence of how the tactic is implemented in Coq or a bug. It's not an issue for me; I just noticed that the AST looked different than some of the other tactics I had tested and wanted to make sure it was correct.
2. I had to update `sertop/sertop_prelude.ml` for proofs using ssreflect tactics to work. I tried using LibAdd instead, but for some reason that didn't work for me, and I had to add `ssreflect` to the list of `coq_init_plugins`.

Other than those two points, serialization is working well for me.

Regarding de-serialization, it would definitely make things easier for me, but I think I can make things work well enough using the `Query` workaround you suggested.

**Comment by ejgallego** [comment] 2018-01-16 02:17
Great, thanks for the feedback @riswords . And no rush in responding of course!

> The subst tactic is tagged as TacAlias in the CoqAst. I'm not sure if this is an expected consequence of how the tactic is implemented in Coq or a bug. It's not an issue for me; I just noticed that the AST looked different than some of the other tactics I had tested and wanted to make sure it was correct.

Indeed, SerAPI does reflect the Coq AST. `subst` is implemented as a `Tactic Extend` command [as many other tactics. Only the tactics defned in `g_ltac.ml4` are "primitive". You could discuss this with Coq upstream but I think this is working as intended and you should be ready to handle "Extend" tactics.

> I had to update sertop/sertop_prelude.ml for proofs using ssreflect tactics to work. I tried using LibAdd instead, but for some reason that didn't work for me, and I had to add ssreflect to the list of coq_init_plugins.

You are totally right about the problems with the initialization code, it is my top priority to fix this now as indeed ssreflect and other libraries are not working correctly. The issue of library management is subtle but I will add soon an option that recovers the Coq default. Please keep using the workaround while the proper fix arrives.

[If you are curious, Coq does a full directory scan to discover libraries. However, this only work in "unix"-like backends, when Coq is running in the browser such as in jsCoq scanning is not an option. Thus SerAPI requires a explicit registration, but this is too strict for regular use so I will recover the scanning mode back]

> Other than those two points, serialization is working well for me.

I'm glad to hear please don't hesitate to open issues / feature requests. An important goal of the project is to get an _usable_ API, so we need to hear back from users.

> Regarding de-serialization, it would definitely make things easier for me, but I think I can make things work well enough using the Query workaround you suggested.

I see, I've bumped it a bit on my TODO list as it is a pity full de-serialization is working but for these "generic arguments".

**Closed** 2018-02-23 20:54 UTC
Labels: bug, in-progress

**Comment by ejgallego** [comment] 2018-02-23 21:15
Full support for "generic arguments" is now in the 8.7 branch. It should appear in OPAM shortly. 

Unfortunately we need to manually register genargs, so please report missing / wrong instances.
